Project_webb/src/application/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from core.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index,name="main"),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^tags/', include('tags.urls', namespace='tags')),
    url(r'^posts/', include('posts.urls', namespace='posts')),


]

Project_webb/src/comments/urls.py
from .views import *
from django.conf.urls import url

urlpatterns = [
    url(r'^$', CommentList.as_view(), name="comment_list"),
]

Project_webb/src/posts/urls.py
from .views import *
from django.conf.urls import url

urlpatterns = [
    url(r'^$', PostList.as_view(), name="post_list"),
    url(
            r'^(?P<pk>\d+)/detail/$',
            post_detail,
            name = 'post_detail'
        )
]

Project_webb/src/questions/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [

    url(r'^$', QuestionList.as_view(), name="question_list"),

    url(
        r'^(?P<pk>\d+)/detail/$',
        question_detail,
        name = 'question_detail'
    )
]

Project_webb/src/tags/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [

    url(r'^$', TagList.as_view(), name="tag_list"),
    url(
        r'^(?P<pk>\d+)/detail/$',
        tag_detail,
        name='tag_detail'
    )

]

Project_webb/src/comments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


class Comment(models.Model):

    created_at = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,blank=True,null=True)
    description = models.TextField(default="",verbose_name=u'Описание коммента')
    #author_comment= models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments',verbose_name=u'Автор комментария',default="")
    post_comment = models.ForeignKey('posts.Post',verbose_name='Пост к комменту',default="")
    question_comment = models.ForeignKey('questions.Question',verbose_name='Вопрос к комменту',related_name='comments_quest',default="")
    #answer = models.ForeignKey('questions.Answer')

    def __str__(self):
        return self.description

Project_webb/src/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    avatar = models.ImageField(upload_to='avatars', blank=True, null=True)

Project_webb/src/posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.conf import settings


class Post(models.Model):

    author_post = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=u'Автор поста', default="")
    title = models.CharField(max_length=200, verbose_name=u'Имя поста', default="None")
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    description = models.TextField(default="", verbose_name=u'Описание поста')
    category_post = models.ManyToManyField('tags.Tag', blank=True, related_name='posts',
                                        verbose_name=u'Категории')
    is_archive = models.BooleanField(default=False, verbose_name=u'Пост в архиве')

    def __unicode__(self):
        return self.title

Project_webb/src/questions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

from django.utils import timezone
import datetime

from django.conf import settings
from django.db import models



class Question(models.Model):

    author_question = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=u'Автор вопроса',default="")
    description = models.TextField(verbose_name=u'Текст вопроса',default="")
    created_at = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,blank=True,null=True)
    category_quest = models.ForeignKey('tags.Tag', related_name='questions', verbose_name=u'Категория вопроса', default="")

    def __unicode__(self):
        return self.description


class Answer(models.Model):

    author_answer = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=u'Автор ответа',default="")
    description = models.TextField(verbose_name=u'Текст ответа', default="")
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    question_answer = models.ForeignKey('questions.Question', related_name='answers', verbose_name=u'Ответ на вопрос', default="")

    def __unicode__(self):
        return self.description

Project_webb/src/tags/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from application import settings
from django.db import models


class Tag(models.Model):

    title = models.CharField(
        max_length=255,
        verbose_name=u'Заголовок категории',
        default=""
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_archive = models.BooleanField(default=False, verbose_name=u'Категория в архиве')
    # post_tag = models.ForeignKey('posts.Post', related_name='categories', default="")

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u'Категория'
        verbose_name_plural = u'Категории'
        ordering = 'title', 'id'

Project_webb/src/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Project_webb/src/comments/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import DetailView, ListView
from .models import Comment

class CommentList(ListView):

    template_name = "comments/comment_list.html"
    model = Comment

Project_webb/src/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,HttpResponse
from posts.models import Post
from questions.models import Question
from tags.models import Tag

def index(request):
    posts = Post.objects.all()[:5]
    questions = Question.objects.all()[:5]
    tags = Tag.objects.all()

    context = {
        'posts':posts,
        'questions':questions,
        'tags':tags,

    }
    return render(request,'core/index.html',context)

Project_webb/src/posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,HttpResponse,get_object_or_404

from django.views.generic import DetailView, ListView
from .models import Post

class PostList(ListView):
    template_name = "posts/post_list.html"
    model = Post

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    context = {
        'post': Post.objects.get(id=pk),
        'categories': post.category_post.all().filter(is_archive=False)
    }

    return render(request, 'posts/post_detail.html', context)

Project_webb/src/questions/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse,get_object_or_404
from django.views.generic import DetailView, ListView
from .models import Question

class QuestionList(ListView):
    template_name = "questions/question_list.html"
    model = Question

def question_detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    return render(request, 'questions/question_detail.html', {'question': question})

Project_webb/src/tags/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse,get_object_or_404
from django.views.generic import DetailView, ListView
from .models import Tag

class TagList(ListView):
    template_name = "tags/tag_list.html"
    model = Tag


def tag_detail(request, pk=None):

    category = get_object_or_404(Tag, id=pk)

    context = {
        'category': Tag.objects.get(id=pk),
        'posts': category.posts.all().filter(is_archive=False)
    }
    return render(request, 'tags/tag_detail.html', context)

Project_webb/src/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse

def users_detail(request,user_id):
    if user_id == "":
        return HttpResponse("List of users")
    return HttpResponse("That's user number {}".format(user_id))
def user_login(request):
    return HttpResponse("User login")
def user_signup(request):
    return HttpResponse("User signup")

Project_webb/src/comments/templates/comments/comment_list.html
{% extends "core/base.html" %}

{% block title %}Список комментов{% endblock %}

{% block content %}
    {% for comment in object_list %}
        <div>
            <a href="{% url "" %}">{{ comment.author }}</a>
            <div>{{ comment.description }}</div>
        </div>
    {% endfor %}
{% endblock %}

Project_webb/src/core/templates/core/base.html
<h1>Parody on stackoverflow</h1>

<h1>{% block title %}{% endblock %}</h1>

{% block content %}
{% endblock %}

Project_webb/src/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.created_at }}
            </div>
           <h1><a href="{% url 'posts:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.description|linebreaksbr }}</p>
        </div>
    {% endfor %}

    {% for question in questions %}
        <div class="question">
            <div class="date">
                {{ question.created_at }}
            </div>
           <h1><a href="{% url 'questions:question_detail' pk=question.pk %}">{{ question.description}}</a></h1>

        </div>
    {% endfor %}


{% endblock %}

Project_webb/src/posts/templates/posts/post_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="post">
        {% if post.created_at %}
            <div class="date">
                {{ post.created_at }}
            </div>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.description|linebreaksbr }}</p>

    {% for tag in categories %}
       <p><a href="{% url 'tags:tag_detail' pk=tag.pk %}">{{ tag }}</a></p>


    {% endfor %}
    </div>

     <a href="{% url "main" %}">Main page</a>
{% endblock %}

Project_webb/src/posts/templates/posts/post_list.html
{% extends 'core/base.html' %}

{% block content %}
    {% for post in object_list %}
        <p>postss</p>
        <div class="post">
            <div class="date">
                {{ post.created_at }}

            </div>

           <h1><a href="{% url 'posts:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.description|linebreaksbr }}</p>
        <p> {{ post.category_post}}</p>
        </div>



{#        {% for tag in post.categories %}#}
{#            <div class = "tags">#}
{#            <h1><a href="{% url 'tags:tag_detail' pk=tag.pk %}">{{ tag.title }}</a></h1>#}
{#            </div>#}
{#        {% endfor %}#}
    {% endfor %}

     <a href="{% url "main" %}">Main page</a>




{% endblock %}

Project_webb/src/questions/templates/questions/question_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="question">
        {% if question.created_at %}
            <div class="date">
                {{ question.created_at }}
            </div>
        {% endif %}

        <p>{{ question.description|linebreaksbr }}</p>

{#     {% for answer in question.answers %}#}
{#         <p> {{ answer.description }}</p>#}
{#         <h3>{{ answer.author_answer }} </h3>#}
{#        {% endfor %}#}
{#        <p> {{ question.category_quest }}</p>#}

    </div>

     <a href="{% url "main" %}">Main page</a>
{% endblock %}

Project_webb/src/questions/templates/questions/question_list.html
{% extends 'core/base.html' %}

{% block content %}
    {% for question in object_list %}
        <div class="question">
            <div class="date">
                {{ question.created_at }}

            </div>

           <h1><a href="{% url 'questions:question_detail' pk=question.pk %}">{{ question.description }}</a></h1>

               </div>



{#        {% for tag in post.categories %}#}
{#            <div class = "tags">#}
{#            <h1><a href="{% url 'tags:tag_detail' pk=tag.pk %}">{{ tag.title }}</a></h1>#}
{#            </div>#}
{#        {% endfor %}#}
    {% endfor %}


     <a href="{% url "main" %}">Main page</a>



{% endblock %}

Project_webb/src/tags/templates/tags/tag_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="tag">

        <h1>{{ category.title }}</h1>

        Posts:
        {% for blog in posts %}
            <p><a href="{% url 'posts:post_detail' pk=blog.pk %}">{{ blog.title }}</a></p>

        {% endfor %}

    </div>

     <a href="{% url "main" %}">Main page</a>
{% endblock %}

Project_webb/src/tags/templates/tags/tag_list.html
{% extends "core/base.html" %}

{% block title %}Список категорий{% endblock %}

{% block content %}
    {% for tag in object_list %}
         {% if tag.is_archive is False %}
        <div>
           <h1><a href="{% url 'tags:tag_detail' pk=tag.pk %}">{{ tag.title }}</a></h1>

        </div>
        {% endif %}
    {% endfor %}

     <a href="{% url "main" %}">Main page</a>
{% endblock %}